-- Extensions
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Master Data Domain
CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES categories(id),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    icon VARCHAR(100),
    sort_order INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

-- Identity Domain
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20) UNIQUE,
    avatar VARCHAR(255),
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    department_id BIGINT REFERENCES departments(id),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(500) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT false,
    device_info VARCHAR(255),
    ip_address VARCHAR(45)
);

-- Default Admin Account (Optional, added as requested/good practice)
INSERT INTO users (name, email, password, role, status)
VALUES ('System Admin', 'admin@dms.com', '$2a$10$3m.j.O0tA42gH9vJvDk3EOCd0X92U9U9X0.q/3bQ0A0a1pZ6q0iM2', 'ADMIN', 'ACTIVE');
-- Note: Password is 'admin' BCrypt hashed.

-- Document Domain
CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    slug VARCHAR(500) NOT NULL UNIQUE,
    description TEXT,
    category_id BIGINT NOT NULL REFERENCES categories(id),
    department_id BIGINT REFERENCES departments(id),
    uploaded_by BIGINT NOT NULL REFERENCES users(id),
    owner_id BIGINT NOT NULL REFERENCES users(id),
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(20) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    thumbnail_path VARCHAR(500),
    preview_object_key VARCHAR(500),
    upload_expires_at TIMESTAMPTZ,
    page_count INT,
    document_code VARCHAR(100) UNIQUE,
    version_number VARCHAR(20) NOT NULL DEFAULT '1.0',
    status VARCHAR(30) NOT NULL DEFAULT 'AWAITING_UPLOAD',
    access_level VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
    view_count INT NOT NULL DEFAULT 0,
    download_count INT NOT NULL DEFAULT 0,
    effective_date DATE,
    expiry_date DATE,
    archived_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT REFERENCES users(id),
    purge_after TIMESTAMPTZ,
    previous_status VARCHAR(30),
    permanently_deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ
);

CREATE TABLE document_department_accesses (
    document_id BIGINT NOT NULL REFERENCES documents(id),
    department_id BIGINT NOT NULL REFERENCES departments(id),
    granted_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (document_id, department_id)
);

CREATE TABLE document_user_accesses (
    document_id BIGINT NOT NULL REFERENCES documents(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    granted_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (document_id, user_id)
);

CREATE TABLE document_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL UNIQUE REFERENCES documents(id),
    extracted_text TEXT,
    extraction_method VARCHAR(50) NOT NULL,
    language VARCHAR(10),
    extraction_status VARCHAR(30) NOT NULL,
    error_message TEXT,
    retry_count INT NOT NULL DEFAULT 0,
    extracted_at TIMESTAMPTZ
);

CREATE TABLE document_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id),
    version_number VARCHAR(20) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'AWAITING_UPLOAD',
    preview_object_key VARCHAR(500),
    upload_expires_at TIMESTAMPTZ,
    changelog TEXT,
    uploaded_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE document_tags (
    document_id BIGINT NOT NULL REFERENCES documents(id),
    tag_id BIGINT NOT NULL REFERENCES tags(id),
    PRIMARY KEY (document_id, tag_id)
);

-- Search Index
CREATE TABLE document_search_index (
    document_id BIGINT PRIMARY KEY REFERENCES documents(id),
    search_vector TSVECTOR NOT NULL,
    title_text TEXT NOT NULL,
    description_text TEXT,
    content_text TEXT,
    document_code_text TEXT,
    tag_text TEXT,
    category_name TEXT,
    department_name TEXT,
    refreshed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Logs
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT REFERENCES users(id),
    action VARCHAR(50) NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    target_id BIGINT,
    old_value JSONB,
    new_value JSONB,
    ip_address VARCHAR(45),
    user_agent VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE access_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    document_id BIGINT NOT NULL REFERENCES documents(id),
    action VARCHAR(30) NOT NULL,
    access_granted BOOLEAN NOT NULL,
    denial_reason VARCHAR(255),
    ip_address VARCHAR(45),
    user_agent VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE search_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    keyword VARCHAR(500),
    filters JSONB,
    result_count INT NOT NULL,
    latency_ms INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- Indexes as defined in DATABASE.md

-- Performance Indexes
CREATE INDEX idx_users_department ON users(department_id);
CREATE INDEX idx_users_status ON users(status);

CREATE INDEX idx_documents_category ON documents(category_id);
CREATE INDEX idx_documents_department ON documents(department_id);
CREATE INDEX idx_documents_uploaded_by ON documents(uploaded_by);
CREATE INDEX idx_documents_owner ON documents(owner_id);
CREATE INDEX idx_documents_status ON documents(status);
CREATE INDEX idx_documents_access_level ON documents(access_level);
CREATE INDEX idx_documents_file_type ON documents(file_type);
CREATE INDEX idx_documents_effective_date ON documents(effective_date);
CREATE INDEX idx_documents_created_at ON documents(created_at);
CREATE INDEX idx_documents_deleted_at ON documents(deleted_at);
CREATE INDEX idx_documents_purge_after ON documents(purge_after);

CREATE INDEX idx_document_versions_doc ON document_versions(document_id);
CREATE INDEX idx_audit_logs_actor_date ON audit_logs(actor_id, created_at);
CREATE INDEX idx_audit_logs_target ON audit_logs(target_type, target_id);
CREATE INDEX idx_access_logs_doc_date ON access_logs(document_id, created_at);
CREATE INDEX idx_access_logs_user_date ON access_logs(user_id, created_at);
CREATE INDEX idx_search_logs_user_date ON search_logs(user_id, created_at);

-- Composite Indexes
CREATE INDEX idx_documents_cat_status_date ON documents(category_id, status, created_at);
CREATE INDEX idx_documents_dept_type ON documents(department_id, file_type);
CREATE INDEX idx_documents_status_purge ON documents(status, purge_after);
CREATE INDEX idx_doc_dept_access_dept ON document_department_accesses(department_id, document_id);
CREATE INDEX idx_doc_user_access_user ON document_user_accesses(user_id, document_id);

-- PostgreSQL Search Indexes (GIN and Trigram)
CREATE INDEX idx_doc_search_vector ON document_search_index USING GIN(search_vector);
CREATE INDEX idx_doc_search_title_trgm ON document_search_index USING GIN(title_text gin_trgm_ops);
CREATE INDEX idx_doc_search_code_trgm ON document_search_index USING GIN(document_code_text gin_trgm_ops);
CREATE INDEX idx_doc_search_tags_trgm ON document_search_index USING GIN(tag_text gin_trgm_ops);
